CREATE TABLE Departments (did INTEGER PRIMARY KEY, name TEXT NOT NULL);
CREATE TABLE Doctors (doc_id INTEGER PRIMARY KEY, name TEXT NOT NULL, did INTEGER NOT NULL);
CREATE TABLE Patients (pid INTEGER PRIMARY KEY, name TEXT NOT NULL, age INTEGER NOT NULL);
CREATE TABLE Appointments (aid INTEGER PRIMARY KEY, doc_id INTEGER NOT NULL, pid INTEGER NOT NULL, date TEXT NOT NULL, status TEXT NOT NULL);